name: Sommelier Cellar Subgraph Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main", "**" ]

env:
  node_version: "14.x"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v2

      # Install Node JS
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: Install JS dependencies
        run: yarn install

      - name: Codegen using the contract abis.
        run: yarn codegen

      - name: Run all unit tests.
        run: yarn test
